services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v3.0.1
    container_name: mealie
    restart: unless-stopped
    ports:
        - "9925:9000"
    deploy:
      resources:
        limits:
          memory: 1000M
    volumes:
      - /home/scallanan/work/mealie/data:/app/data
    environment:
      # Set Backend ENV Variables Here
      ALLOW_SIGNUP: "false"
      PUID: 1000
      PGID: 1000
      TZ: Europe/Dublin
      BASE_URL: https://menu.alma

volumes:
  mealie-data:

