services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:latest
    container_name: mealie
    restart: unless-stopped
    networks:
      - proxy
    deploy:
      resources:
        limits:
          memory: 1000M
    volumes:
      - ./data:/app/data
    environment:
      # Set Backend ENV Variables Here
      ALLOW_SIGNUP: "false"
      PUID: 1000
      PGID: 1000
      TZ: Europe/Dublin
      BASE_URL: https://menu.alma
    labels:
      traefik.enable: true
      traefik.http.routers.mealie.rule: Host(`menu.alma`)
      traefik.http.routers.mealie.entrypoints: web
      wud.tag.include: ^v\d+\.\d+\.\d+$$
      wud.link.template: https://github.com/mealie-recipes/mealie/releases/tag/v$${major}.$${minor}.$${patch}
      wud.display.icon: si:mealie
volumes:
  mealie-data: null
networks:
  proxy:
    external: true
    name: proxy
